# Generated by Django 3.2.5 on 2022-02-05 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activityregister_classroom_classsubject_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityregister',
            name='attendance',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
