# Generated by Django 3.2.5 on 2022-02-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220204_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image_profile',
            field=models.ImageField(upload_to='face_photos/$None/$<django.db.models.fields.CharField>/'),
        ),
    ]
