# Generated by Django 3.2.5 on 2022-02-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image_profile',
            field=models.ImageField(upload_to='face_photos/<bound method Field.value_to_string of <django.db.models.fields.related.ForeignKey>>/<bound method Field.value_to_string of <django.db.models.fields.CharField>>/'),
        ),
    ]
