# Generated by Django 3.2.5 on 2022-02-05 05:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_student_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image_profile',
            field=models.ImageField(upload_to=api.models.user_directory_path),
        ),
    ]
